"""add watched_threads table

Revision ID: 5091786e556a
Revises: 005
Create Date: 2026-04-22 13:33:24.885780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5091786e556a'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('graph_message_id', sa.String(), nullable=False),
    sa.Column('graph_conversation_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('has_reply', sa.Boolean(), nullable=False),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_message_id')
    )
    op.create_index(op.f('ix_watched_threads_graph_conversation_id'), 'watched_threads', ['graph_conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watched_threads_graph_conversation_id'), table_name='watched_threads')
    op.drop_table('watched_threads')
    # ### end Alembic commands ###
