"""add sent_email_scans, expand watched_threads

Revision ID: 6250de3c6c8c
Revises: 5091786e556a
Create Date: 2026-04-22 13:47:35.150018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6250de3c6c8c'
down_revision: Union[str, None] = '5091786e556a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_email_scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('graph_message_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('body_preview', sa.Text(), nullable=False),
    sa.Column('expects_reply', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('user_decision', sa.String(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_message_id')
    )
    op.add_column('watched_threads', sa.Column('source', sa.String(), nullable=False))
    op.add_column('watched_threads', sa.Column('ai_expects_reply', sa.Boolean(), nullable=True))
    op.add_column('watched_threads', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('watched_threads', sa.Column('ai_reasoning', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watched_threads', 'ai_reasoning')
    op.drop_column('watched_threads', 'ai_confidence')
    op.drop_column('watched_threads', 'ai_expects_reply')
    op.drop_column('watched_threads', 'source')
    op.drop_table('sent_email_scans')
    # ### end Alembic commands ###
